test: add browserstack wdio

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,22 +1,49 @@
 version: 2.1
 
-orbs:
-  gcp-cli: circleci/gcp-cli@2.1.0
-
-## FIXME / SECURITY: do not use this cluster to push the APK
-commands:
-  gke-auth:
-    steps:
-      - run:
-          name: Authenticate on gcloud
-          command: |
-            echo ${GCLOUD_SERVICE_KEY} > gcloud-service-key.json
-            gcloud auth activate-service-account --key-file=gcloud-service-key.json
-            gcloud config set project ${GOOGLE_PROJECT_ID}
-            gcloud container clusters get-credentials testnet-cluster --region us-central1-a --project ${GOOGLE_PROJECT_ID}
-
 jobs:
-  build_ios:
+  android_test:
+    docker:
+      - image: circleci/android:api-30
+    resource_class: large
+    environment:
+      TERM: dumb
+      JAVA_OPTS: -Xms512m -Xmx2g
+      GRADLE_OPTS: -Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"
+    working_directory: ~/galoy-mobile
+    shell: /bin/bash --login -o pipefail
+    steps:
+      - checkout:
+          path: ~/galoy-mobile
+      - run: sudo apt-get update
+      - run: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
+      - run: sudo apt-get install -y gnupg2 gcc g++ make nodejs
+      - run: sudo npm install -g yarn
+      - run: yarn install
+      - run:
+          name: Build APK
+          command: cd android && ./gradlew assembleDebug
+      - run:
+          name: App upload and Set app id in environment variable.
+          command: |
+            cd android
+            APP_UPLOAD_RESPONSE=$(curl -u "$BROWSERSTACK_USER:$BROWSERSTACK_ACCESS_KEY" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@app/build/outputs/apk/debug/app-debug.apk")
+            APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
+            if [ $APP_ID != null ]; then
+              echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
+              echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
+              source $BASH_ENV;
+              echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
+            else
+              UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+              echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+              exit 1;
+            fi
+      - run:
+          name: Run Test on Android
+          command: |
+            ./node_modules/.bin/wdio android/browserstack.js
+  
+  ios_test:
     macos:
       xcode: 13.1.0
     working_directory: ~/galoy-mobile
@@ -40,7 +67,6 @@ jobs:
       - restore_cache:
           key: 1-yarn-{{ checksum "yarn.lock" }}-pod1-{{ checksum "ios/Podfile.lock" }}
       - run: yarn install
-      # - run: git diff "ios/Podfile.lock" | cat
       - save_cache:
           key: 1-yarn-{{ checksum "yarn.lock" }}-pod1-{{ checksum "ios/Podfile.lock" }}
           paths:
@@ -49,123 +75,34 @@ jobs:
       - run: yarn jest
       - run: sed -i'' -e "s/GOOGLE_SERVICE_FIREBASE_API_KEY/$GOOGLE_SERVICE_FIREBASE_API_KEY/" ios/GoogleService-Info.plist
       - run:
-          name: fastlane
-          command: cd ios && bundle exec fastlane beta
+          name: Build IPA
+          command: cd ios && bundle exec fastlane build_ipa
           no_output_timeout: 15m
-      - run: git config credential.helper 'cache --timeout=120'
-      - run: git config --global user.name "circleci-bot"
-      - run: git config --global user.email "bot@circleci.com"
-      - run: git config pull.rebase false
-      - run: git pull https://${GITHUB_TOKEN}@github.com/GaloyMoney/galoy-mobile.git $CIRCLE_BRANCH
-      - run: git commit -a -m "new ios build [ci skip]"
-      - run: git reset -- GoogleService-Info.plist
-      - run: git push -q https://${GITHUB_TOKEN}@github.com/GaloyMoney/galoy-mobile.git $CIRCLE_BRANCH
-      - store_artifacts:
-          path: ios/output
-      - store_test_results:
-          path: ios/output/scan
-
-  build_android:
-    docker:
-      - image: circleci/android:api-30
-    resource_class: large
-    environment:
-      TERM: dumb
-      JAVA_OPTS: -Xms512m -Xmx2g
-      GRADLE_OPTS: -Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"
-    working_directory: ~/galoy-mobile
-    shell: /bin/bash --login -o pipefail
-    steps:
-      - checkout:
-          path: ~/galoy-mobile
-      - run: sudo apt-get update
-      - run: sudo apt-get install gnupg2
-      - run: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
-      - run: sudo apt-get install -y nodejs
-      - run: sudo apt-get install gcc g++ make
-      - run: sudo npm install -g yarn
-      - run: gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
-      - run: curl -sL https://get.rvm.io | bash -s stable --ruby
-      - run: source /home/circleci/.rvm/scripts/rvm
-      - run: rvm install 2.5
-      - run: rvm use 2.5 --default
-      - run: gem install fastlane -NV
-
-      - run: cd android && bundle config set deployment 'true'
-      - run: cd android && bundle check || bundle install
-
-      - run: echo $ANDROID_SERVICE_ACCOUNT_UPLOAD | base64 -d > android/api-8350101450647692243-59029-b9bec84a7e5a.json
-      - run: echo $RELEASE_KEYSTORE | base64 -d > android/release.keystore
-      - run: echo $RELEASE_KEYSTORE | base64 -d > android/app/release.keystore
-
-      - run: node -v
-      - run: npm -v
-      - run: ruby -v
-      - run: fastlane -v
-      - run: yarn -v
-
-      - run: yarn install
-      - run: yarn jest
-      - run: echo $JAVA_OPTS
-      - run: echo $GRADLE_OPTS
-      - run: cd android && fastlane android beta
-
-      # - gke-auth
-      # - run:
-      #     name: upload latest apk to gcs
-      #     command: |
-      #       cd ~/galoy-mobile/android/app/build
-      #       VERSION_CODE=$(jq .elements[0].apkData.versionCode ./intermediates/instant_app_manifest/release/output.json)
-      #       cd ./outputs/apk/release/
-      #       gsutil cp ./app-release.apk gs://bitcoin-beach-wallet/"$VERSION_CODE".apk
-      #       gsutil cp ./app-release.apk gs://bitcoin-beach-wallet/latest.apk
-
-      - run: git config credential.helper 'cache --timeout=120'
-      - run: git config --global user.name "circleci-bot"
-      - run: git config --global user.email "bot@circleci.com"
-      - run: git config pull.rebase false
-      - run: git pull origin $CIRCLE_BRANCH
-      - run: cd ~/galoy-mobile
-      - run: git add --force android/app/build/generated/sourcemaps/react/release
-      - run: git commit -a -m "new android build [ci skip]"
-      - run: git push -q https://${GITHUB_TOKEN}@github.com/GaloyMoney/galoy-mobile.git $CIRCLE_BRANCH
-
-  update_locale:
-    working_directory: ~/galoy-mobile
-    docker:
-      - image: cimg/base:2020.01
-    resource_class: small
-    steps:
-      - checkout:
-          path: ~/galoy-mobile
-      - run: sed -i "s/__TOKEN__/$PHRASE_TOKEN/" .phrase.yml
-      - run: wget https://github.com/phrase/phrase-cli/releases/download/2.0.13/phrase_linux_amd64
-      - run: chmod +x ./phrase_linux_amd64
-      - run: ./phrase_linux_amd64 push
-      - run: ./phrase_linux_amd64 pull
-      - run: git config credential.helper 'cache --timeout=120'
-      - run: git config --global user.name "circleci-bot"
-      - run: git config --global user.email "bot@circleci.com"
-      - run: git config pull.rebase false
-      - run: |
-          if [[ $(-- . ':!.phrase.yml') ]]; then
-            git commit -a -m "update translation file [ci skip]" -- . ':!.phrase.yml'
-            git push -q https://${GITHUB_TOKEN}@github.com/GaloyMoney/galoy-mobile.git $CIRCLE_BRANCH
-          else
-            echo "nothing to commit"
-          fi
+      - run:
+          name: App upload and Set app id in environment variable.
+          command: |
+            cd ios
+            APP_UPLOAD_RESPONSE=$(curl -u "$BROWSERSTACK_USER:$BROWSERSTACK_ACCESS_KEY" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@output/gym/Bitcoin Beach.ipa")
+            APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
+            if [ $APP_ID != null ]; then
+              echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
+              echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
+              source $BASH_ENV;
+              echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
+            else
+              UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+              echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+              exit 1;
+            fi
+      - run:
+          name: Run Test on iOS
+          command: |
+            ./node_modules/.bin/wdio ios/browserstack.js
 
 workflows:
-  mobile:
+  android:
     jobs:
-      - hold_build_mobile:
-          type: approval
-      - update_locale:
-          requires:
-            - hold_build_mobile
-      - build_ios:
-          requires:
-            - update_locale
-      - build_android:
-          requires:
-            - update_locale
+      - android_test
+  ios:
+    jobs:
+      - ios_test
